# -*- coding: utf-8 -*-
"""Indian Election - 2019 (Complete Analysis)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/swethakswarna/indian-election-2019-complete-analysis.b97dabf5-de14-4d93-bede-a50ef72a45ee.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250422/auto/storage/goog4_request%26X-Goog-Date%3D20250422T170208Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D1ed3c20faa248132fe925eb98fc836832b15d870a1ecdddde52e813d8c8eef730444d3989a6732486432e499a7c2bbc132eaf12b05679f51e3bb30fc9fbd95958f76d999645cd6933cf6531700651faafc952e0d7bd5955c276162009a3d6ee0b886cb2cbd231d28f25986e8cf694bb735acb01dee0585f702ad8c5490718fce832d601d52c6c0fa36bd5ffa95281402025f9079e48eeaed3f2af39a8066cfb9c8e7948bc0bf20d7cac6949dfb9e91f1bbcceceae2d4bd44cf6af00648287f5e082a0893fe6deb69511374d1af22ed513f526dbed4179a719cc467d021d3048853a5fb2b181e61df7ea4b64a17619b1c89613c9e08c652ec2a03f44ac6f688b2
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
prakrutchauhan_indian_candidates_for_general_election_2019_path = kagglehub.dataset_download('prakrutchauhan/indian-candidates-for-general-election-2019')

print('Data source import complete.')

"""# Indian Elections - 2019


![](https://d2c7ipcroan06u.cloudfront.net/wp-content/uploads/2019/05/2019-696x392.jpg)

In this Notebook, I will be providing you complete Analysis of Indian Election held in 2019.

The 2019 Indian general election was held in **seven phases from 11 April to 19 May 2019 to constitute the 17th Lok Sabha**. The votes were counted and the result declared on 23 May. **About 911 million people were eligible to vote, and voter turnout was over 67 % the highest ever, as well as the highest ever participation by women voters.**

**The Bharatiya Janata Party won 303 seats, further increasing its substantial majority and the BJP-led National Democratic Alliance (NDA) won 353 seats.The BJP won 37.36% of votes, while the NDA's combined vote was 45% of the 60.37 crore votes that were polled.**

**The Indian National Congress won just 52 seats, and the Congress-led United Progressive Alliance won 91. Other parties and their alliances won 98 seats.**
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install pycountry
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objects as go
import plotly.offline as py
import plotly.express as px
import pycountry
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
print('Successfully loaded')

data = pd.read_csv('/content/LS_2.0 2.csv')
data.head()

data = data.rename(columns={"CRIMINAL\nCASES": "Criminal", "GENERAL\nVOTES": "Genral_votes","POSTAL\nVOTES":"Postal_votes","TOTAL\nVOTES":"Total_votes"})
data.head()

round(data.isnull().sum()/len(data.index),2)
data = data.dropna() ## deleting all the NaN values for Analysis purposes

Num_cons = data.groupby('STATE')['CONSTITUENCY'].nunique().sort_values(ascending = False).reset_index()

ax = px.bar(Num_cons,y='CONSTITUENCY',x='STATE',color = 'CONSTITUENCY', title='The Number of Constituencies from each State')
ax.show()

"""### Uttar Pradesh has the highest number of CONSTITUENCY - 80
### The second is from Maharashtra - 48

"""

# Data Cleaning
data['Criminal'] = data['Criminal'].replace('Not Available','0').astype('int')

data['EDUCATION'] = data['EDUCATION'].replace('Post Graduate\n','Post Graduate')
data['EDUCATION'] = data['EDUCATION'].replace('Not Available','Others')
education = data['EDUCATION'].value_counts().reset_index()
education.columns = ['EDUCATION','COUNT']
ax = px.bar(education,x = 'EDUCATION', y = 'COUNT',color = 'EDUCATION', title= 'Education Level of the Candidates')
ax.show()

"""1. We have **503 candidates with Post Graduation Degree.**
2. **441 have Graduate Degree.**
3. **336 have Graduate Professional Degree (Students who opt to pursue graduate study seek master or doctoral degrees in a particular discipline).**
4. **There are 256 Candidates with 12th Pass Certificates.**
5. **73 Candidates have Doctrate degree.**
6. **35 Candidtes have No Degree at all.**

### Total number of candidates 2018.
"""

winner = data[data['WINNER']==1]
ax = px.bar(winner,x = 'EDUCATION',y = 'WINNER', title='Winning Candidates Educational Degree').update_xaxes(categoryorder = "total descending")
ax.show()

"""### The Highest number of Winners were Post Graduate."""

young_winner = data[data['WINNER']==1]
young_winner = young_winner.sort_values('AGE').head(10)
ax = px.bar(young_winner,x = 'NAME',y = 'AGE',color = 'AGE',hover_data = ['PARTY','STATE','CONSTITUENCY'], title='Youngest Winners')
ax.show()

"""## The Youngest Winners

### Top 3 Winner Details:

- 1st | Name - GODDETI MADHAVI	| Age - 26 | Gender - Female | Education - Graduate Professional | Constituency - ARUKU | Party - YSRCP

- 2nd  | Name - Nusrat Jahan Ruhi	| Age - 28 | Gender - Female | Education - 12th Pass | Constituency - BASIRHAT	 | Party - AITC

- 3rd  | Name - TEJASVI SURYA	| Age - 28 | Gender - Male | Education - Graduate Professional	 | Constituency - BANGALORE SOUTH	 | Party - BJP
"""

old_winner = data[data['WINNER']==1]
old_winner = old_winner.sort_values('AGE',ascending = False).head(10)
ax = px.bar(old_winner,x = 'NAME',y = 'AGE',color = 'AGE',hover_data = ['PARTY','STATE','CONSTITUENCY'], title = 'Oldest Winners and their Details:')
ax.show()

"""### The Oldest Winner

- 1st | Name - DR. SHAFIQUR REHMAN BARQ		| Age - 86 | Gender - Male | Education - Graduate | Constituency - SAMBHAL	 | Party - SP

"""

sns.distplot(data['AGE'],
             kde=False,
             hist_kws=dict(edgecolor="black", linewidth=2),
             color='#00BFC4')

criminal_cases = data.groupby('PARTY')['Criminal'].sum().reset_index().sort_values('Criminal',ascending=False).head(30)
ax = px.bar(criminal_cases, x = 'PARTY',y = 'Criminal',color = 'PARTY', title='Total Criminal Cases by respective parties')
ax.show()

"""## Criminal Cases
1. BJP - 898 Cases
2. Congress - 734 Cases
"""

crime = data[data['WINNER']==1]
criminal_cases = crime.groupby('PARTY')['Criminal'].sum().reset_index().sort_values('Criminal',ascending=False).head(30)
ax = px.bar(criminal_cases, x = 'PARTY',y = 'Criminal',color = 'PARTY', title='Winning Parties with Number of Criminal Cases')
ax.show()

## changing the datatype
data['GENDER'] = data['GENDER'].astype('category')
data['WINNER'] = data['WINNER'].astype('category')

Female_winners = data[(data['WINNER']==1) & (data['GENDER']=='FEMALE')]
ax = px.histogram(Female_winners, 'STATE', title = 'Female Winners from different States')
ax.show()

"""### Highest number of Female winners were from West Bengal"""

male_winners = data[(data['WINNER']==1) & (data['GENDER']=='MALE')]
ax = px.histogram(male_winners, 'STATE', title='Male Winners from different States')
ax.show()

votes = data.groupby('STATE')['Total_votes'].sum().sort_values(ascending = False).reset_index()
ax = px.bar(votes,x = 'STATE',y = 'Total_votes',color='STATE', title='Total Votes cast State Wise')
ax.show()

"""### Total votes casted is highest in UP were the highest."""

category = data['CATEGORY'].value_counts().reset_index()
category.columns= ['CATEGORY','COUNT']
ax = px.bar(category,x = 'CATEGORY', y = 'COUNT', color = 'CATEGORY')
ax.show()

df = data[data['WINNER']==1]
category = df['CATEGORY'].value_counts().reset_index()
category.columns= ['CATEGORY','COUNT']
ax = px.bar(category,x = 'CATEGORY', y = 'COUNT', color = 'CATEGORY', title='Winners from Various Categories')
ax.show()

"""### I Hope you find this Analysis useful for your Knowledge and understanding of Politics in India.

### Feel free to Input your thoughts on any graph or Data that you might have found interesting.
"""